// Tables - Part 2
export const TABLES_P2 = `
CREATE TABLE IF NOT EXISTS "DaytimeService" (
  "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "price" DOUBLE PRECISION NOT NULL,
  "category" TEXT NOT NULL, "duration" TEXT NOT NULL DEFAULT '', "description" TEXT NOT NULL DEFAULT '',
  "active" BOOLEAN NOT NULL DEFAULT true, "providerId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "DaytimeBooking" (
  "id" TEXT NOT NULL PRIMARY KEY, "serviceId" TEXT NOT NULL,
  "guestName" TEXT NOT NULL, "guestPhone" TEXT NOT NULL,
  "date" TEXT NOT NULL, "time" TEXT NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1,
  "unitPrice" DOUBLE PRECISION NOT NULL, "totalCost" DOUBLE PRECISION NOT NULL,
  "paidAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "paymentStatus" "PaymentStatusType" NOT NULL DEFAULT 'PENDING', "paymentMethod" "PaymentMethodType",
  "notes" TEXT NOT NULL DEFAULT '', "providerId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "Expense" (
  "id" TEXT NOT NULL PRIMARY KEY, "date" TEXT NOT NULL, "category" TEXT NOT NULL,
  "description" TEXT NOT NULL, "amount" DOUBLE PRECISION NOT NULL,
  "vendor" TEXT NOT NULL DEFAULT '', "paymentMethod" "PaymentMethodType" NOT NULL,
  "receiptNo" TEXT NOT NULL DEFAULT '', "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "providerId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "ExpenseCategory" (
  "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "nameAm" TEXT NOT NULL,
  "color" TEXT NOT NULL, "icon" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "Resource" (
  "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "category" TEXT NOT NULL,
  "quantity" DOUBLE PRECISION NOT NULL, "unit" TEXT NOT NULL,
  "minLevel" DOUBLE PRECISION NOT NULL DEFAULT 0, "costPerUnit" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "supplier" TEXT NOT NULL DEFAULT '', "lastRestocked" TIMESTAMP(3), "providerId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "Payment" (
  "id" TEXT NOT NULL PRIMARY KEY, "reservationId" TEXT, "daytimeBookingId" TEXT,
  "amount" DOUBLE PRECISION NOT NULL, "method" "PaymentMethodType" NOT NULL,
  "referenceNo" TEXT NOT NULL DEFAULT '', "notes" TEXT NOT NULL DEFAULT '', "providerId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
`;