// Tables - Part 3
export const TABLES_P3 = `
CREATE TABLE IF NOT EXISTS "Notification" (
  "id" TEXT NOT NULL PRIMARY KEY, "title" TEXT NOT NULL, "message" TEXT NOT NULL,
  "type" "NotificationType" NOT NULL DEFAULT 'INFO', "isRead" BOOLEAN NOT NULL DEFAULT false,
  "link" TEXT, "providerId" TEXT, "userId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "HousekeepingTask" (
  "id" TEXT NOT NULL PRIMARY KEY, "roomId" TEXT NOT NULL,
  "type" "HousekeepingTaskType" NOT NULL, "status" "HousekeepingTaskStatus" NOT NULL DEFAULT 'PENDING',
  "assignedTo" TEXT, "scheduledDate" TEXT NOT NULL, "notes" TEXT NOT NULL DEFAULT '',
  "completedAt" TIMESTAMP(3), "providerId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "Review" (
  "id" TEXT NOT NULL PRIMARY KEY, "guestId" TEXT NOT NULL, "reservationId" TEXT NOT NULL,
  "rating" INTEGER NOT NULL, "comment" TEXT NOT NULL DEFAULT '',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "ActivityLog" (
  "id" TEXT NOT NULL PRIMARY KEY, "message" TEXT NOT NULL, "type" TEXT NOT NULL DEFAULT 'INFO',
  "providerId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "Settings" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "guestHouseName" TEXT NOT NULL DEFAULT 'Guest House', "ownerName" TEXT NOT NULL DEFAULT '',
  "address" TEXT NOT NULL DEFAULT '', "phone" TEXT NOT NULL DEFAULT '',
  "email" TEXT NOT NULL DEFAULT '', "currency" TEXT NOT NULL DEFAULT 'ETB',
  "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0, "language" TEXT NOT NULL DEFAULT 'en',
  "logo" TEXT, "checkInTime" TEXT NOT NULL DEFAULT '14:00', "checkOutTime" TEXT NOT NULL DEFAULT '12:00',
  "providerId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
`;