// Tables - Part 4 (Police & Subscription)
export const TABLES_P4 = `
CREATE TABLE IF NOT EXISTS "SuspectedPerson" (
  "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "phone" TEXT NOT NULL DEFAULT '',
  "idNumber" TEXT NOT NULL DEFAULT '', "idType" TEXT NOT NULL DEFAULT '',
  "nationality" TEXT NOT NULL DEFAULT '', "address" TEXT NOT NULL DEFAULT '',
  "description" TEXT NOT NULL DEFAULT '', "severity" "SuspectSeverity" NOT NULL DEFAULT 'MEDIUM',
  "is_active" BOOLEAN NOT NULL DEFAULT true, "registeredBy" TEXT NOT NULL DEFAULT '',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "SuspectMatch" (
  "id" TEXT NOT NULL PRIMARY KEY, "suspectedPersonId" TEXT NOT NULL, "matchType" TEXT NOT NULL,
  "guestName" TEXT NOT NULL, "guestPhone" TEXT NOT NULL DEFAULT '',
  "guestIdNumber" TEXT NOT NULL DEFAULT '', "providerName" TEXT NOT NULL DEFAULT '',
  "providerId" TEXT NOT NULL DEFAULT '', "reservationId" TEXT, "daytimeBookingId" TEXT,
  "details" TEXT NOT NULL DEFAULT '', "isRead" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "AuditLog" (
  "id" TEXT NOT NULL PRIMARY KEY, "officerName" TEXT NOT NULL DEFAULT '',
  "action" TEXT NOT NULL, "targetId" TEXT, "targetType" TEXT DEFAULT '',
  "details" TEXT, "ipAddress" TEXT DEFAULT '',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "Geofence" (
  "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "address" TEXT NOT NULL DEFAULT '',
  "latitude" DOUBLE PRECISION NOT NULL DEFAULT 0, "longitude" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "radius" DOUBLE PRECISION NOT NULL DEFAULT 1000, "severity" TEXT NOT NULL DEFAULT 'HIGH',
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "FrequentStayAlert" (
  "id" TEXT NOT NULL PRIMARY KEY, "guestName" TEXT NOT NULL, "guestPhone" TEXT NOT NULL DEFAULT '',
  "guestIdNumber" TEXT NOT NULL DEFAULT '', "providerNames" TEXT NOT NULL DEFAULT '[]',
  "stayCount" INTEGER NOT NULL DEFAULT 0, "avgDaysBetween" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "riskLevel" TEXT NOT NULL DEFAULT 'MEDIUM', "isReviewed" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "Subscription" (
  "id" TEXT NOT NULL PRIMARY KEY, "providerId" TEXT NOT NULL,
  "startDate" TIMESTAMP(3) NOT NULL, "endDate" TIMESTAMP(3) NOT NULL,
  "cycle" "SubscriptionCycle" NOT NULL DEFAULT 'MONTHLY', "price" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Subscription_providerId_key" UNIQUE ("providerId")
);
CREATE TABLE IF NOT EXISTS "SubscriptionPayment" (
  "id" TEXT NOT NULL PRIMARY KEY, "subscriptionId" TEXT NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL, "cycle" "SubscriptionCycle" NOT NULL,
  "periodStart" TIMESTAMP(3) NOT NULL, "periodEnd" TIMESTAMP(3) NOT NULL,
  "markedBy" TEXT NOT NULL, "notes" TEXT NOT NULL DEFAULT '',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "PoliceAlertConfig" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "emailEnabled" BOOLEAN NOT NULL DEFAULT false, "emailRecipients" TEXT NOT NULL DEFAULT '[]',
  "smsEnabled" BOOLEAN NOT NULL DEFAULT false, "smsRecipients" TEXT NOT NULL DEFAULT '[]',
  "escalationDelayMins" INTEGER NOT NULL DEFAULT 60, "criticalImmediate" BOOLEAN NOT NULL DEFAULT true,
  "anomalyDetectionEnabled" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
`;
