// Tables - Part 1
export const TABLES_P1 = `
CREATE TABLE IF NOT EXISTS "Provider" (
  "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "ownerName" TEXT NOT NULL, "phone" TEXT NOT NULL,
  "email" TEXT NOT NULL DEFAULT '', "address" TEXT NOT NULL DEFAULT '',
  "type" TEXT NOT NULL DEFAULT 'GUEST_HOUSE',
  "licenseNo" TEXT NOT NULL DEFAULT '', "licenseFile" TEXT NOT NULL DEFAULT '',
  "status" "ProviderStatus" NOT NULL DEFAULT 'PENDING',
  "latitude" DOUBLE PRECISION NOT NULL DEFAULT 9.02, "longitude" DOUBLE PRECISION NOT NULL DEFAULT 38.75,
  "approvedBy" TEXT, "approvedAt" TIMESTAMP(3), "rejectionReason" TEXT NOT NULL DEFAULT '',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "User" (
  "id" TEXT NOT NULL PRIMARY KEY, "username" TEXT NOT NULL, "password" TEXT NOT NULL,
  "role" "UserRole" NOT NULL DEFAULT 'STAFF', "name" TEXT NOT NULL,
  "permissions" TEXT NOT NULL DEFAULT '["reservations","guests"]',
  "policeRank" TEXT NOT NULL DEFAULT '', "providerId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "User_username_key" UNIQUE ("username")
);
CREATE TABLE IF NOT EXISTS "Room" (
  "id" TEXT NOT NULL PRIMARY KEY, "number" TEXT NOT NULL, "name" TEXT NOT NULL,
  "type" "RoomType" NOT NULL, "pricePerNight" DOUBLE PRECISION NOT NULL,
  "floor" INTEGER NOT NULL, "capacity" INTEGER NOT NULL,
  "status" "RoomStatus" NOT NULL DEFAULT 'AVAILABLE',
  "amenities" TEXT NOT NULL, "description" TEXT NOT NULL, "image" TEXT, "providerId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Room_number_providerId_key" UNIQUE ("number", "providerId")
);
CREATE TABLE IF NOT EXISTS "Guest" (
  "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "phone" TEXT NOT NULL,
  "email" TEXT NOT NULL DEFAULT '', "idNumber" TEXT NOT NULL DEFAULT '',
  "idType" TEXT NOT NULL DEFAULT '', "nationality" TEXT NOT NULL DEFAULT '',
  "address" TEXT NOT NULL DEFAULT '', "notes" TEXT NOT NULL DEFAULT '',
  "vip" BOOLEAN NOT NULL DEFAULT false, "totalSpent" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "totalStays" INTEGER NOT NULL DEFAULT 0, "providerId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "Reservation" (
  "id" TEXT NOT NULL PRIMARY KEY, "guestId" TEXT NOT NULL, "roomId" TEXT NOT NULL,
  "checkIn" TEXT NOT NULL, "checkOut" TEXT NOT NULL, "nights" INTEGER NOT NULL,
  "roomRate" DOUBLE PRECISION NOT NULL, "totalCost" DOUBLE PRECISION NOT NULL,
  "paidAmount" DOUBLE PRECISION NOT NULL DEFAULT 0, "balance" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "paymentStatus" "PaymentStatusType" NOT NULL DEFAULT 'PENDING', "paymentMethod" "PaymentMethodType",
  "status" "ReservationStatus" NOT NULL DEFAULT 'UPCOMING', "notes" TEXT NOT NULL DEFAULT '',
  "actualCheckIn" TIMESTAMP(3), "actualCheckOut" TIMESTAMP(3),
  "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0, "discountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "providerId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
`;